#repos:
#  - repo: https://github.com/gruntwork-io/pre-commit
#    rev: v0.1.21 # Get the latest from: https://github.com/gruntwork-io/pre-commit/releases
#    hooks:
#      - id: terraform-fmt
repos:
- repo: https://github.com/antonbabenko/pre-commit-terraform
  rev: v1.79.1 # Get the latest from: https://github.com/antonbabenko/pre-commit-terraform/releases
  hooks:
    - id: terraform_fmt
      #    - id: terraform_docs
    - id: terraform_tflint
        
